### ISSUE TITLE
dependency on laravel framework

### ISSUE THREAD

**Issue by AleshchenkoMaksim** [amestsantim/voucherator#1]
Your library can't work without laravel collections, because you use `collect()` function from laravel.
But you wrote in the readme that 

> The only voucher (alphanumeric code) generator you will ever need for PHP.

**Comment by amestsantim** [comment]
You are absolutely right. I will eliminate this dependency and update.
Thanks!

**Comment by amestsantim** [comment]
I have now updated the package to use a standalone collection library (tightenco/collect) to eliminate its dependency on laravel. 
I believe this issue is now resolved.
